### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by abijij** [abijij/appDelivery#5]
Cuando se crea un nuevo usuario automático ingresa a la aplicación  y al momento de   direccionarnos a la pantalla de perfil del  usuario nos manda a la pantalla de inicio.

Se deberá implementar de manera correcta el inicio de sesión, al momento de registrar un usuario solo deberá de registrar sin iniciar sesión automáticamente

**Comment by alexromiti00** [comment]
Fixed
